### ISSUE TITLE
Link to COOL system not working

### ISSUE THREAD

**Issue by mikemadden42** [cisagov/join-cisagov#5]
# 🐛 Summary #

The link to the COOL system is not working.

## To reproduce ##

1. Browse to https://github.com/cisagov/join-cisagov/blob/develop/README.md
2. Click on the [COOL](https://github.com/cisagov/cool-system) link.
3. The link results in a 404. 

## Expected behavior ##

Information on the the COOL system should be present.  I wonder if the repository is private?

## Any helpful log output or screenshots ##

![image](https://user-images.githubusercontent.com/5888518/146659929-8369183f-dfd0-401f-97eb-ca4df487063c.png)

**Comment by alnash28** [comment]
@mikemadden42 iWonder. The [ Cloud Optimized Operational Lab (COOL)](https://www.libhunt.com/compare-cool-system-vs-sig-security) appears to be DISCONTINUED. However, it would be nice to have a reference architecture guide or similar for all of us [r/homelab](https://www.reddit.com/r/homelab/), [r/cybersecurity ](https://www.reddit.com/r/cybersecurity/)OR [r/sysadmin](https://www.reddit.com/r/sysadmin/) enthusiasts

**Comment by jbilinski** [comment]
added [PR 29](https://github.com/cisagov/join-cisagov/pull/29) #29
